### ISSUE TITLE
RuntimeError: main thread is not in main loop

### ISSUE THREAD

**Issue by Veitch-Li** [vahidk/TensorflowFramework#1]
I met a problem when I run your code, can you solve it?

WARNING:tensorflow:uid (from tensorflow.contrib.learn.python.learn.estimators.run_config) is experimental and may change or be removed at any time, and without warning.
INFO:tensorflow:Using config: {'_model_dir': 'output/cnn_classifier_mnist', '_save_checkpoints_secs': None, '_num_ps_replicas': 0, '_keep_checkpoint_max': 5, '_session_config': gpu_options {
  allow_growth: true
}
allow_soft_placement: true
, '_tf_random_seed': None, '_task_type': None, '_environment': 'local', '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fa70e534d50>, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_num_worker_replicas': 0, '_task_id': 0, '_save_summary_steps': 100, '_save_checkpoints_steps': 200, '_evaluation_master': '', '_keep_checkpoint_every_n_hours': 10000, '_master': '', '_log_step_count_steps': 100}
WARNING:tensorflow:uid (from tensorflow.contrib.learn.python.learn.estimators.run_config) is experimental and may change or be removed at any time, and without warning.
WARNING:tensorflow:From /home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:269: __init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.
Loaded 60000 images of size [28, 28].
Loaded 60000 labels.
INFO:tensorflow:Create CheckpointSaverHook.
2017-09-13 16:49:51.776469: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-13 16:49:51.776488: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-13 16:49:51.776492: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-13 16:49:51.776496: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-13 16:49:51.776499: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
INFO:tensorflow:Saving checkpoints for 1 into output/cnn_classifier_mnist/model.ckpt.
INFO:tensorflow:predictions:0: 8
INFO:tensorflow:labels:0: 1
INFO:tensorflow:predictions:0: 8
INFO:tensorflow:labels:0: 9
INFO:tensorflow:predictions:0: 8
INFO:tensorflow:labels:0: 1
Loaded 10000 images of size [28, 28].
Loaded 10000 labels.
INFO:tensorflow:Starting evaluation at 2017-09-13-08:50:01
INFO:tensorflow:Restoring parameters from output/cnn_classifier_mnist/model.ckpt-1
INFO:tensorflow:Finished evaluation at 2017-09-13-08:50:04
INFO:tensorflow:Saving dict for global step 1: accuracy = 0.2329, global_step = 1, loss = 2.23739
INFO:tensorflow:Validation (step 1): loss = 2.23739, global_step = 1, accuracy = 0.2329
INFO:tensorflow:loss = 2.30457, step = 1
2017-09-13 16:51:48.898924: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: exceptions.RuntimeError: main thread is not in main loop
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/liwq/Code/DataSet/TensorflowFramework/trainer.py", line 205, in <module>
    tf.app.run()
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/liwq/Code/DataSet/TensorflowFramework/trainer.py", line 201, in main
    hparams=get_params())
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 209, in run
    return _execute_schedule(experiment, schedule)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 46, in _execute_schedule
    return task()
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 502, in train_and_evaluate
    self.train(delay_secs=0)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 280, in train
    hooks=self._train_monitors + extra_hooks)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 672, in _call_train
    hooks=hooks)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 241, in train
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 686, in _train_model
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 518, in run
    run_metadata=run_metadata)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 862, in run
    run_metadata=run_metadata)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 818, in run
    return self._sess.run(*args, **kwargs)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 972, in run
    run_metadata=run_metadata)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 818, in run
    return self._sess.run(*args, **kwargs)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: exceptions.RuntimeError: main thread is not in main loop
	 [[Node: PyFunc = PyFunc[Tin=[DT_FLOAT, DT_INT64], Tout=[DT_UINT8], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](IteratorGetNext, ArgMax)]]

Caused by op u'PyFunc', defined at:
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/liwq/Code/DataSet/TensorflowFramework/trainer.py", line 205, in <module>
    tf.app.run()
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/liwq/Code/DataSet/TensorflowFramework/trainer.py", line 201, in main
    hparams=get_params())
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 209, in run
    return _execute_schedule(experiment, schedule)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 46, in _execute_schedule
    return task()
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 502, in train_and_evaluate
    self.train(delay_secs=0)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 280, in train
    hooks=self._train_monitors + extra_hooks)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 672, in _call_train
    hooks=hooks)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 241, in train
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 630, in _train_model
    model_fn_lib.ModeKeys.TRAIN)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 615, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/liwq/Code/DataSet/TensorflowFramework/trainer.py", line 132, in _model_fn
    predictions, loss, metrics = model_fn(features, labels, mode, params)
  File "model/cnn_classifier.py", line 46, in model
    summary.labeled_image("images", images, predictions)
  File "common/summary.py", line 49, in labeled_image
    figs = tf.py_func(_visualize_images, [images, labels], tf.uint8)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 203, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_script_ops.py", line 36, in _py_func
    name=name)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnknownError (see above for traceback): exceptions.RuntimeError: main thread is not in main loop
	 [[Node: PyFunc = PyFunc[Tin=[DT_FLOAT, DT_INT64], Tout=[DT_UINT8], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](IteratorGetNext, ArgMax)]]

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/matplotlib/_pylab_helpers.py", line 92, in destroy_all
    manager.destroy()
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 619, in destroy
    self.window.destroy()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1862, in destroy
    for c in self.children.values(): c.destroy()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2100, in destroy
    self.tk.call('destroy', self._w)
RuntimeError: main thread is not in main loop
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/matplotlib/_pylab_helpers.py", line 92, in destroy_all
    manager.destroy()
  File "/home/liwq/.virtualenvs/py2env/local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 619, in destroy
    self.window.destroy()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1862, in destroy
    for c in self.children.values(): c.destroy()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2100, in destroy
    self.tk.call('destroy', self._w)
RuntimeError: main thread is not in main loop

**Comment by vahidk** [comment]
Do you have the latest version? I suspect either the code or tf is old. Try:
pip install --upgrade tensorflow-gpu
git pull
