### ISSUE TITLE
Max-pooling

### ISSUE THREAD

**Issue by vrbkind** [vahidk/TensorflowFramework#2]
Hi,

I tried to apply the AlexNet model with max-pooling on MNIST (by adding pool_method="max" in model/alexnet. py), not with strided_conv2d.
But I get the following error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/vrbkind/test/TensorflowFramework/trainer.py", line 128, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/alexandre/test/TensorflowFramework/trainer.py", line 124, in main
    MODELS[FLAGS.model], DATASETS[FLAGS.dataset], FLAGS.hparams))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 218, in run
    return _execute_schedule(experiment, schedule)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 46, in _execute_schedule
    return task()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 625, in train_and_evaluate
    self.train(delay_secs=0)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 367, in train
    hooks=self._train_monitors + extra_hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 807, in _call_train
    hooks=hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 302, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 711, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 694, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "common/optimizer.py", line 146, in _model_fn
    stats = tf.profiler.profile(tf.get_default_graph(), options=opts)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/profiler/model_analyzer.py", line 312, in profile
    graph, op_log, run_meta, add_trace=cmd == 'code')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/profiler/tfprof_logger.py", line 146, in _merge_default_with_oplog
    graph, run_meta, add_trace=add_trace, add_trainable_var=add_trainable_var)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/profiler/tfprof_logger.py", line 88, in _get_logged_ops
    graph, op.node_def, REGISTERED_FLOP_STATS)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2362, in get_stats_for_node_def
    result = stats_func(graph, node)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/profiler/internal/flops_registry.py", line 378, in _max_pool_grad_flops
    max_pool_ops = kernel_area * orig_out_shape.num_elements()
TypeError: unsupported operand type(s) for *: 'long' and 'NoneType'

I use Tensorflow 1.4.0 with Python 2.7.12 (the problem is the same with 3.5.7)

I thank you in advance for your help.

**Comment by ychfan** [comment]
`tf.profiler` conflcts with pooling layers, try to remove lines from 143 to 148 in `common/optimizer.py`

**Comment by vahidk** [comment]
I tested this and this doesn't seems to work fine. Not sure what the problem your was.
